# -*- coding: utf-8 -*-
"""Generate detailed per-add-on specification markdown files."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "add-ons" / "specs"
OUT.mkdir(parents=True, exist_ok=True)

# Each add-on: research-enriched spec fields
ADDONS: list[dict] = [
    {
        "file": "01-simulateur-mensualite.md",
        "title": "Simulateur de mensualité",
        "priority": "P0",
        "category": "Accession / Axe 2–3",
        "summary": "Calcule acompte, durée et mensualité en FCFA pour vente étalée (terrains) et location-vente (bâti).",
        "problem": "Les acheteurs ne savent pas s'ils peuvent suivre. Chez Immobilier-au-Sénégal le paiement échelonné reste un bandeau marketing, pas un outil.",
        "market": "Barèmes retenus en analyse interne: acompte 10% max si bien < 1M FCFA, sinon ~30%; durée 12–36 mois; frais de dossier 25–50k (terrain) / 50–100k (bâti). Voir docs/first analysis.",
        "users": "Acquéreur, agent, diaspora",
        "synergy": "Entrée de parcours T; alimente réservation + dashboard acquéreur; share card WhatsApp.",
        "inputs": [
            "prix_bien (FCFA)",
            "acompte_pct ou acompte_fixe",
            "duree_mois (12|24|36…)",
            "frais_dossier",
            "mode: etale | loc_vente",
        ],
        "outputs": [
            "mensualite",
            "total_paye",
            "tableau echeances",
            "CTA reserver / WhatsApp",
            "lien share OG",
        ],
        "ux": [
            "Bloc sur fiche bien si paymentModes contient etale/loc_vente",
            "Page /outils/mensualite (SEO)",
            "Export image/PDF pour WhatsApp",
        ],
        "functional": [
            "Formule: (prix - acompte) / duree (+ option frais lissés)",
            "Règles admin éditables (min acompte par palier de prix)",
            "Disclaimer: simulation indicative, pas un crédit bancaire",
            "Lead capture optionnelle (tél/WhatsApp) avant PDF",
        ],
        "data_model": [
            "Listing.paymentModes[], Listing.price",
            "PlanRule {minPrice, maxPrice, minDownPct, maxTenor}",
            "SimulationLog {listingId?, inputs, result, userId?}",
        ],
        "api": [
            "POST /api/addons/mensualite/simulate",
            "GET /api/addons/mensualite/rules",
        ],
        "monetization": "Gratuit → conversion réservation / frais dossier. Pas de fee sur le calcul.",
        "kpis": "sim_start, sim_complete, lead_rate, reservation_rate",
        "risks": "Confusion avec prêt bancaire; afficher clairement 'facilité vendeur via agence'.",
        "v1": "Formule simple + CTA",
        "later": "Co-acquisition multi-payeurs; pénalités affichées; Wave auto-debit preview",
        "sources": [
            "docs/first analysis/q1–q3.md",
            "docs/proptech-analysis.md",
            "https://immobilier-au-senegal.com/ (concept concurrent faible)",
        ],
    },
    {
        "file": "02-simulateur-construction.md",
        "title": "Simulateur coût de construction",
        "priority": "P0",
        "category": "Construction / Terrains",
        "summary": "Estime le budget pour construire une maison (FCFA/m²) selon surface, finition et zone — branché sur fiches terrain.",
        "problem": "Acheter le terrain sans chiffrer la maison mène à l'échec projet; les guides SN insistent sur +10–15% d'imprévus.",
        "market": "Repères 2025–2026: standard régions ~250–350k FCFA/m²; clé en main ~300–500k; Dakar souvent +15–25%. Maison 100 m² ≈ 30–50 M FCFA hors terrain. Architecte obligatoire si coût > ~30 M FCFA.",
        "users": "Acheteur terrain, diaspora, agent",
        "synergy": "Après simu mensualité; pack Terrain→Maison; share 'terrain+construction'.",
        "inputs": [
            "surface_m2 (50–600)",
            "niveaux: R+0 | R+1",
            "finition: eco | standard | standing",
            "zone: dakar | petite_cote | interieur",
            "options: cloture, fosse, vrd, imprevus_10_15, tva_18",
            "listing_id (préremplit localisation)",
        ],
        "outputs": [
            "fourchette min–max FCFA",
            "prix/m²",
            "détail postes",
            "CTA devis constructeur / archi",
            "PDF",
        ],
        "ux": [
            "Bandeau fiche terrain: 'Construire ici ?'",
            "/outils/construire",
            "Résultat + 'Budget total projet' deep-link",
        ],
        "functional": [
            "Barèmes admin par zone/finition (table ConstructionRate)",
            "Multiplicateurs options (% ou forfait)",
            "Disclaimer fourchette ±10–15%, hors terrain",
            "Si total > 30M: hint 'architecte recommandé/obligatoire'",
        ],
        "data_model": [
            "ConstructionRate {zone, finish, pricePerSqmMin, pricePerSqmMax, updatedAt}",
            "ConstructionOption {code, label, type: pct|fixed, value}",
        ],
        "api": [
            "POST /api/addons/construction/simulate",
            "CRUD admin /api/admin/construction-rates",
        ],
        "monetization": "Lead partenaires BTP/archi; commission 2–5% sur contrat signé; PDF email-gate.",
        "kpis": "sim_from_listing, partner_leads, pdf_downloads",
        "risks": "Responsabilité devis — toujours 'indicatif'; barèmes à recalibrer avec partenaires locaux.",
        "v1": "Barèmes + options + CTA",
        "later": "Types de maison (catalogue plans); photos; lien suivi chantier",
        "sources": [
            "https://keur-immo.com/senegal/construction-maison-senegal/",
            "https://investissementimmoafrique.com/simulateur-cout-construction-maison-senegal/",
            "https://investissementimmoafrique.com/calculateur-du-cout-de-construction/",
            "https://hubcephas.com/estimateur-en-ligne/",
        ],
    },
    {
        "file": "03-simulateur-budget-total.md",
        "title": "Simulateur budget total projet",
        "priority": "P0",
        "category": "Accession",
        "summary": "Agrège terrain + mode de paiement + construction + frais d'acquisition (notaire/mutation) en un seul total.",
        "problem": "Les acheteurs voient le prix du terrain seul et sous-estiment cash jour J + chantier.",
        "market": "Sur TF: droits d'enregistrement ~5%, formalité foncière ~1%, émoluments notaire dégressifs (ex. 4,5%→0,75%) + TVA 18% sur honoraires. Total frais souvent cité ~7–15% selon dossier.",
        "users": "Acquéreur, diaspora",
        "synergy": "Compose add-ons 01+02+21; bundle Terrain Serein.",
        "inputs": ["listing ou prix_terrain", "mode paiement", "params construction", "include_frais_notaire"],
        "outputs": ["cash_initial", "flux_mensuels", "budget_construction", "frais", "grand_total", "timeline"],
        "ux": ["/outils/budget-projet", "CTA depuis fiches terrain"],
        "functional": [
            "Orchestration des 3 calculateurs",
            "Barème notaire configurable (tranches)",
            "Affichage multi-devise optionnel (EUR/USD indicatif)",
        ],
        "data_model": ["NotaryFeeBracket", "réutilise ConstructionRate + PlanRule"],
        "api": ["POST /api/addons/budget-total/simulate"],
        "monetization": "Lead pack diligence+bornage+construction.",
        "kpis": "completion_rate, bundle_attach",
        "risks": "Barèmes fiscaux à valider avec notaire partenaire; disclaimer.",
        "v1": "Somme indicative",
        "later": "Scénarios A/B (comptant vs étalé)",
        "sources": [
            "https://immoconnexion.com/acheter-un-terrain-au-senegal/",
            "https://www.senpages.com/dossiers/acheter-un-terrain",
            "https://nadiaimmoservices.blog/frais-notaire-senegal/",
            "https://jiwall.com/droit-immobilier/tout-savoir-sur-les-tarifs-des-notaires-au-senegal/",
        ],
    },
    {
        "file": "04-estimation-vendeur.md",
        "title": "Estimation de bien (vendeur)",
        "priority": "P0",
        "category": "Vente / Axe 1",
        "summary": "Fourchette de prix pour propriétaires — tunnel vers mandat de vente.",
        "problem": "Sans estimation crédible, le vendeur part sur Facebook/Expat à un mauvais prix.",
        "market": "Pratique standard des agences SN (estimation pro). Prix/m² très variables Dakar vs Petite Côte vs intérieur.",
        "users": "Propriétaire, agent",
        "synergy": "Dashboard proprio 'Revendre'; alimente Axe 1; comps pour carte prix/m².",
        "inputs": ["type", "quartier/ville", "surface", "pieces", "etat", "photos?"],
        "outputs": ["fourchette", "prix_m2_ref", "CTA mandat WhatsApp/RDV"],
        "ux": ["/estimer", "widget site", "espace proprio"],
        "functional": [
            "Formulaire + scoring zone",
            "Comps manuels/admin au début",
            "Création lead CRM statut=estimate",
            "Disclaimer non expertise judiciaire",
        ],
        "data_model": ["EstimateRequest", "CompSale", "Lead"],
        "api": ["POST /api/addons/estimate"],
        "monetization": "Conversion mandat (commission vente).",
        "kpis": "requests, mandate_conversion",
        "risks": "Attentes vendeur irréalistes — cadrer avec comps visibles.",
        "v1": "Règles + revue agent sous 24h",
        "later": "AVM + carte chaleur",
        "sources": ["docs/positioning.md", "docs/competitive-analysis.md"],
    },
    {
        "file": "05-guides-seo.md",
        "title": "Guides & pages outils SEO",
        "priority": "P0",
        "category": "Acquisition",
        "summary": "Contenu éditorial FR indexable qui pousse vers simulateurs et catalogue.",
        "problem": "Sans contenus, Google envoie le trafic vers Expat-Dakar / CoinAfrique.",
        "market": "Intentions fortes: construction coût, TF vs bail, caution, frais notaire, acheter depuis France.",
        "users": "Prospect organique",
        "synergy": "Chaque guide deep-link vers add-ons P0/P1.",
        "inputs": ["CMS MD/MDX"],
        "outputs": ["trafic", "leads"],
        "ux": ["/guides/[slug]", "hub /outils"],
        "functional": [
            "10 piliers v1",
            "Schema Article + FAQ",
            "CTA sticky simulateur",
            "Revue annuelle des chiffres",
        ],
        "data_model": ["ContentEntry"],
        "api": ["CMS / static generation Next.js"],
        "monetization": "CAC organique.",
        "kpis": "organic_landings, guide_to_tool_ctr",
        "risks": "Chiffres périmés — dater les articles.",
        "v1": "Piliers listés dans add-ons.md",
        "later": "Vidéo / YouTube embeds",
        "sources": [
            "https://www.myafric.com/fr/acheter-senegal-depuis-france-diaspora/",
            "https://keur-immo.com/senegal/construction-maison-senegal/",
        ],
    },
    {
        "file": "06-pack-terrain-maison.md",
        "title": "Pack Terrain → Maison",
        "priority": "P1",
        "category": "Construction",
        "summary": "Offre packagée: simulation + checklist permis + shortlist archi/constructeurs partenaires.",
        "problem": "Le client est perdu entre géomètre, urbanisme, devis BTP.",
        "market": "Plans catalogue ~100–500k FCFA; sur-mesure archi dès ~500k+. Permis exige NICAD, plans, etc.",
        "users": "Acheteur terrain post-réservation",
        "synergy": "Suit 02+11+12+13; upsell suivi chantier diaspora.",
        "inputs": ["listing", "budget", "délai souhaité"],
        "outputs": ["checklist", "3 devis partenaires", "prochain RDV"],
        "ux": ["Dashboard acquéreur checklist", "page vente pack"],
        "functional": [
            "Wizard étapes",
            "Assignation partenaires par zone",
            "Statuts dossier",
        ],
        "data_model": ["BuildPackOrder", "Partner"],
        "api": ["POST /api/addons/build-pack"],
        "monetization": "Forfait conseil agence et/ou commission partenaires.",
        "kpis": "pack_sold, partner_accept_rate",
        "risks": "Ne pas promettre délais urbanisme.",
        "v1": "Checklist + matching manuel",
        "later": "Matching auto + paiements jalons",
        "sources": [
            "https://www.ecsinformatique.com/quel-est-le-cout-de-realisation-de-plan-de-maison-en-2024/",
            "https://unmondesenegal.com/acheter-terrain-senegal/",
            "https://kapitalconseilimmobilier.com/",
        ],
    },
    {
        "file": "07-bornage-geometre.md",
        "title": "Bornage / géomètre",
        "priority": "P1",
        "category": "Foncier",
        "summary": "Mise en relation avec géomètre-expert agréé pour plan de bornage opposable + NICAD.",
        "problem": "Sans bornage, écarts de superficie fréquents (ex. 400 m² promis → 270 m² réels).",
        "market": "Seul un géomètre-expert agréé produit un bornage opposable. Pas de barème officiel public fiable — devis obligatoire. NICAD requis pour opérations / permis.",
        "users": "Acheteur terrain, diaspora",
        "synergy": "Avant construction; bundle Terrain Serein avec diligence.",
        "inputs": ["parcelle refs", "TF/bail/NICAD si connu", "localisation GPS"],
        "outputs": ["demande devis", "RDV", "upload plan PDF"],
        "ux": ["CTA fiche terrain", "checklist post-achat"],
        "functional": [
            "Form lead → partenaires géomètres par région",
            "Upload documents finaux au coffre-fort dossier",
        ],
        "data_model": ["ServiceRequest type=survey", "Document"],
        "api": ["POST /api/addons/survey-request"],
        "monetization": "Frais dossier agence + commission/apporter d'affaires.",
        "kpis": "requests, completed_surveys",
        "risks": "Délais terrain; ne pas afficher un prix inventé.",
        "v1": "Lead + suivi statut",
        "later": "Paiement Wave du devis via plateforme",
        "sources": [
            "https://unmondesenegal.com/acheter-terrain-senegal/",
            "https://immoconnexion.com/acheter-un-terrain-au-senegal/",
        ],
    },
    {
        "file": "08-due-diligence-fonciere.md",
        "title": "Due diligence foncière",
        "priority": "P1",
        "category": "Foncier / Confiance",
        "summary": "Vérification titre / litiges / hypothèque avant paiement — rapport horodaté (partenaire type YAWEET).",
        "problem": "Fraudes diaspora: faux titres, indivision, chevauchements. L'état de droits réels à la Conservation est la base.",
        "market": "Certificat / état de droits réels peu cher (ordre centaines–milliers FCFA) mais crucial. YAWEET vend un rapport diligence complet pour diaspora.",
        "users": "Acquéreur, diaspora, agence (avant publication annonce)",
        "synergy": "Gate 'we publish ads'; avant séquestre; bundle Diaspora Full.",
        "inputs": ["réfs TF/bail/NICAD", "docs vendeur", "localisation"],
        "outputs": ["rapport PDF", "score confiance", "go/no-go"],
        "ux": ["CTA 'Vérifier avant de payer'", "workflow interne listing approval"],
        "functional": [
            "Commande partenaire API ou formulaire",
            "Statuts: requested → in_progress → delivered",
            "Bloquer boost listing sans diligence minimale (policy)",
        ],
        "data_model": ["DiligenceOrder", "Listing.verificationStatus"],
        "api": ["POST /api/addons/diligence"],
        "monetization": "Markup sur rapport partenaire ou forfait agence.",
        "kpis": "orders, block_rate_bad_titles",
        "risks": "Délais admin DGID; dépendance partenaire.",
        "v1": "Process manuel + PDF",
        "later": "Intégration partenaire",
        "sources": [
            "https://yaweet.com/",
            "https://www.senpages.com/dossiers/acheter-un-terrain",
            "https://immoconnexion.com/acheter-un-terrain-au-senegal/",
        ],
    },
    {
        "file": "09-permis-construire-cu.md",
        "title": "Permis de construire & certificat d'urbanisme",
        "priority": "P1",
        "category": "Construction / Admin",
        "summary": "Checklist + accompagnement dossier autorisation de construire (NICAD, plans, assainissement…).",
        "problem": "Confusion entre achat terrain et droit de construire — dossiers incomplets = retards.",
        "market": "Autorisation de construire distincte de l'achat; NICAD souvent exigé; archi si seuil coût dépassé.",
        "users": "Propriétaire terrain, diaspora",
        "synergy": "Pack Terrain→Maison; plans types.",
        "inputs": ["NICAD", "plans", "devis descriptif"],
        "outputs": ["checklist dynamique", "suivi dépôt", "partenaires archi"],
        "ux": ["Wizard dashboard", "notifications"],
        "functional": ["Templates pièces par commune", "Upload coffre-fort"],
        "data_model": ["PermitCase"],
        "api": ["CRUD permit cases"],
        "monetization": "Forfait accompagnement + lead archi.",
        "kpis": "cases_opened, permits_obtained",
        "risks": "Règles communales variables — ne pas garantir délai.",
        "v1": "Checklist + human assist",
        "later": "Suivi statut API si dispo",
        "sources": [
            "https://unmondesenegal.com/acheter-terrain-senegal/",
            "https://keur-immo.com/senegal/construction-maison-senegal/",
            "https://kapitalconseilimmobilier.com/",
        ],
    },
    {
        "file": "10-simulateur-pret-a-batir.md",
        "title": "Simulateur terrain nu → prêt à bâtir",
        "priority": "P1",
        "category": "Viabilisation",
        "summary": "Estime clôture, fosse, bornage, branchements eau/électricité — coûts oubliés post-achat.",
        "problem": "Viabilisation non chiffrée tue le budget (ex. couples à Diamniadio dépassés après ramblai/fosse/taxes).",
        "market": "Pas de barème officiel SENELEC/SEN'EAU unique; devis locaux. Ajouter comme options forfaitaires éditables.",
        "users": "Acheteur terrain",
        "synergy": "Complète simu construction; bundle Prêt à bâtir.",
        "inputs": ["périmètre_m", "besoin_eau", "besoin_elec", "zone"],
        "outputs": ["total options", "détail", "CTA partenaires"],
        "ux": ["Étape après simu construction"],
        "functional": ["Table forfaits admin", "Disclaimer devis réels"],
        "data_model": ["SitePrepRate"],
        "api": ["POST /api/addons/site-prep/simulate"],
        "monetization": "Leads clôture/forage/VRD.",
        "kpis": "attach_rate_after_land_purchase",
        "risks": "Coûts très site-dépendants.",
        "v1": "Forfaits indicatifs",
        "later": "Devis partenaires en ligne",
        "sources": [
            "https://unmondesenegal.com/acheter-terrain-senegal/",
            "https://www.youtube.com/watch?v=JQ0_Uf6xXYU",
        ],
    },
    {
        "file": "11-caution-locative.md",
        "title": "Caution locative digitale",
        "priority": "P1",
        "category": "Location / Fintech",
        "summary": "Partenariat type Cautiona: avance de caution au bailleur, remboursement échelonné du locataire.",
        "problem": "Cautions de 3–4 mois bloquent l'accès au logement à Dakar.",
        "market": "Cautiona SN: demande app, scoring, validation ~24h, avance au proprio, frais service (~15% modèle annoncé). Traçabilité = enjeu régulation.",
        "users": "Locataire, bailleur, agence",
        "synergy": "Signature bail Axe 4; bundle Locataire Tranquille; scoring réutilisable.",
        "inputs": ["loyer", "duree_caution_mois", "KYC locataire"],
        "outputs": ["éligibilité", "redirect partenaire / deep-link", "statut dossier"],
        "ux": ["Checkout location", "Dashboard locataire"],
        "functional": [
            "Intégration partenaire (referral) — pas prêteur en propre v1",
            "Consentement partage data scoring",
        ],
        "data_model": ["CautionReferral"],
        "api": ["POST /api/addons/caution/refer"],
        "monetization": "Referral fee partenaire.",
        "kpis": "referrals, funded_cautions, lease_close_rate",
        "risks": "Régulation fintech; ne pas balancer le risque crédit sur l'agence.",
        "v1": "Referral + tracking",
        "later": "API native si partenariat profond",
        "sources": [
            "https://aps.sn/une-fintech-mise-sur-la-digitalisation-pour-faciliter-lacces-au-logement/",
            "https://www.euroquity.com/en/company/cautiona",
            "https://lequotidien.sn/cherte-des-loyers-le-dg-de-cautiona-interpelle-le-president-faye-pour-une-regulation-numerique/",
        ],
    },
    {
        "file": "12-etat-des-lieux-digital.md",
        "title": "État des lieux digital",
        "priority": "P1",
        "category": "Location / Gestion",
        "summary": "Checklist photo + signature entrée/sortie, stockée au dashboard (locataire & proprio).",
        "problem": "Litiges caution sans preuve; conseils terrain: ne jamais payer caution sans EDL précis.",
        "market": "Noflaye expose déjà bail + EDL + quittances 24/7 — standard à atteindre.",
        "users": "Agent, locataire, proprio",
        "synergy": "Gestion locative; pack remise des clés; assurance.",
        "inputs": ["photos pièces", "compteurs", "mobilier", "signatures"],
        "outputs": ["PDF EDL", "baseline pour sortie"],
        "ux": ["App agent mobile-first", "Dashboard locataire"],
        "functional": [
            "Templates par type bien",
            "Horodatage + geo optionnelle",
            "Comparaison entrée/sortie",
        ],
        "data_model": ["InventoryReport", "InventoryItem"],
        "api": ["POST /api/addons/inventory"],
        "monetization": "Inclus mandat gestion; upsell pack sortie.",
        "kpis": "edl_completion, dispute_rate",
        "risks": "Qualité photo agent — formation.",
        "v1": "Form + PDF",
        "later": "IA détection dégradations",
        "sources": [
            "https://www.noflaye.sn/",
            "https://2sage-alba.com/destinations/international/afrique/senegal/dakar/",
        ],
    },
    {
        "file": "13-assurance-mrh.md",
        "title": "Assurance habitation (MRH)",
        "priority": "P1",
        "category": "Location / Assurance",
        "summary": "Devis / souscription assurance multirisque habitation à la signature du bail via courtier partenaire.",
        "problem": "Locataires non couverts; bailleurs exposés.",
        "market": "Agences SN vendent déjà assurance en partenariat (ex. 2SMS + assureurs). À brancher au checkout bail.",
        "users": "Locataire",
        "synergy": "Bundle Locataire Tranquille; EDL.",
        "inputs": ["adresse", "loyer", "surface", "valeur mobilier"],
        "outputs": ["devis", "attestation PDF"],
        "ux": ["Étape post-bail"],
        "functional": ["Lead courtier ou iframe partenaire"],
        "data_model": ["InsuranceReferral"],
        "api": ["POST /api/addons/insurance/mrh"],
        "monetization": "Commission courtage.",
        "kpis": "attach_rate_at_lease",
        "risks": "Conformité distribution assurance.",
        "v1": "Referral",
        "later": "Devis instantané API",
        "sources": [
            "https://linkedin.com/company/2sms-immobilier-sarl",
            "docs/add-ons.md",
        ],
    },
    {
        "file": "14-assurance-pno.md",
        "title": "Assurance PNO (propriétaire non occupant)",
        "priority": "P1",
        "category": "Gestion / Assurance",
        "summary": "Upsell assurance PNO pour bailleurs sous mandat de gestion.",
        "problem": "Proprios diaspora/local sans couverture des risques locatifs.",
        "market": "Pratique courante des agences full-service SN.",
        "users": "Propriétaire",
        "synergy": "Dashboard proprio; bundle Bailleur Pro.",
        "inputs": ["bien", "loyer", "type occupancy"],
        "outputs": ["devis PNO"],
        "ux": ["Portail proprio"],
        "functional": ["Referral courtier"],
        "data_model": ["InsuranceReferral type=pno"],
        "api": ["POST /api/addons/insurance/pno"],
        "monetization": "Commission.",
        "kpis": "pno_attach_rate",
        "risks": "Même cadre distribution.",
        "v1": "CTA + partenaire",
        "later": "Renouvellement auto rappel",
        "sources": ["docs/positioning.md", "docs/add-ons.md"],
    },
    {
        "file": "15-inspection-diaspora.md",
        "title": "Inspection à distance (diaspora)",
        "priority": "P1",
        "category": "Diaspora",
        "summary": "Visite filmée + rapport photo/vidéo horodaté pour terrain, logement ou chantier.",
        "problem": "La diaspora paie sur WhatsApp photos non indépendantes — risque majeur.",
        "market": "MyAfric: séparer vendeur / inspecteur / notaire. QualiBTP / SENIMMO: suivi chantier + reporting diaspora. Forfait USD/EUR.",
        "users": "Diaspora buyer/owner",
        "synergy": "Avant paiement; escrow; suivi chantier.",
        "inputs": ["adresse/GPS", "type: land|home|site", "checklist"],
        "outputs": ["rapport PDF", "galerie", "go/no-go notes agent"],
        "ux": ["Compte diaspora", "commande /inspect"],
        "functional": [
            "Assign agent indépendant du vendeur",
            "Slots RDV",
            "Livraison 48–72h",
        ],
        "data_model": ["InspectionOrder"],
        "api": ["POST /api/addons/inspections"],
        "monetization": "Forfait payant (Wave/carte).",
        "kpis": "orders, nps, prevented_bad_deals (qualitatif)",
        "risks": "Conflit d'intérêt si même agent vend — policy séparation.",
        "v1": "Process manuel + upload",
        "later": "Live video call",
        "sources": [
            "https://www.myafric.com/fr/acheter-senegal-depuis-france-diaspora/",
            "https://www.coupefile-immobilier.com/senegal-terrain-a-vendre-et-diaspora-comment-acheter-a-distance-en-confiance/",
            "https://linkedin.com/company/qualibtp",
            "https://agencesenimmo.com/",
        ],
    },
    {
        "file": "16-multi-devise.md",
        "title": "Affichage multi-devise (FCFA / EUR / USD)",
        "priority": "P1",
        "category": "Diaspora / UX",
        "summary": "Prix catalogue et simulateurs en FCFA + conversion indicative EUR/USD.",
        "problem": "Diaspora lit en euros; frictions de compréhension.",
        "market": "Guides diaspora affichent souvent équivalents €.",
        "users": "Diaspora",
        "synergy": "Toutes fiches + simus + share cards.",
        "inputs": ["montant XOF", "taux feed"],
        "outputs": ["montant affiché + disclaimer taux"],
        "ux": ["Toggle devise header"],
        "functional": ["FX rate cache quotidien", "Toujours stocker XOF"],
        "data_model": ["FxRate"],
        "api": ["GET /api/fx"],
        "monetization": "Conversion (indirect).",
        "kpis": "toggle_usage, diaspora_session_share",
        "risks": "Taux indicatif seulement.",
        "v1": "EUR+USD",
        "later": "GBP",
        "sources": ["https://www.myafric.com/fr/acheter-senegal-depuis-france-diaspora/"],
    },
    {
        "file": "17-notaire-pack-juridique.md",
        "title": "Notaire / pack juridique",
        "priority": "P1",
        "category": "Vente / Closing",
        "summary": "Checklist + mise en relation notaire; rappel séquestre pour paiements sécurisés.",
        "problem": "Paiements Wave/WU directs au vendeur = arnaque classique diaspora.",
        "market": "Mutation TF obligatoire chez notaire. Séquestre étude. Frais totaux souvent 7–15%.",
        "users": "Acheteur, vendeur",
        "synergy": "Axe 1 closing; diligence; procuration.",
        "inputs": ["dossier pièces"],
        "outputs": ["checklist", "RDV notaire partenaire", "estimation frais"],
        "ux": ["Tunnel post-offre acceptée"],
        "functional": ["Apporteur d'affaires notaire", "Calculateur frais"],
        "data_model": ["ClosingCase"],
        "api": ["POST /api/addons/notary-lead"],
        "monetization": "Apporteur d'affaires.",
        "kpis": "closings_assisted",
        "risks": "Indépendance notaire — client choisit.",
        "v1": "Checklist + leads",
        "later": "Suivi étapes mutation",
        "sources": [
            "https://www.coupefile-immobilier.com/senegal-terrain-a-vendre-et-diaspora-comment-acheter-a-distance-en-confiance/",
            "https://immoconnexion.com/acheter-un-terrain-au-senegal/",
            "https://jiwall.com/droit-immobilier/tout-savoir-sur-les-tarifs-des-notaires-au-senegal/",
        ],
    },
    {
        "file": "18-calculateur-frais-acquisition.md",
        "title": "Calculateur frais d'acquisition",
        "priority": "P1",
        "category": "Transparence / SEO",
        "summary": "Estime droits d'enregistrement, formalité foncière, émoluments notaire + TVA.",
        "problem": "Surprise à la signature si frais non anticipés.",
        "market": "Enregistrement ~5%; formalité ~1%; émoluments dégressifs 4,5%/3%/1,5%/0,75% + TVA 18%.",
        "users": "Acheteur",
        "synergy": "Budget total; pack notaire; guides SEO.",
        "inputs": ["prix", "type: tf_ancien | autre"],
        "outputs": ["détail frais", "total", "disclaimer"],
        "ux": ["/outils/frais-notaire", "fiche vente"],
        "functional": ["Barème admin tranches"],
        "data_model": ["NotaryFeeBracket"],
        "api": ["POST /api/addons/notary-fees/simulate"],
        "monetization": "Confiance + lead notaire.",
        "kpis": "tool_usage",
        "risks": "Régimes particuliers (TVA immo neuf) — cases à cocher.",
        "v1": "Régime classique TF",
        "later": "Plus de régimes fiscaux",
        "sources": [
            "https://nadiaimmoservices.blog/frais-notaire-senegal/",
            "https://www.senpages.com/dossiers/acheter-un-terrain",
        ],
    },
    {
        "file": "19-pack-clim.md",
        "title": "Pack climatisation + entretien",
        "priority": "P1",
        "category": "Confort / Énergie",
        "summary": "Devis splits + contrat entretien annuel via partenaires élec/clim.",
        "problem": "Confort Dakar non négociable; pannes = tickets gestion.",
        "market": "Installateurs locaux (Batigo, Namory…). Entretien récurrent = revenu partenaire.",
        "users": "Proprio, locataire (si autorisé), acquéreur loc-vente",
        "synergy": "Maintenance marketplace; bundle Maison Confort; solaire.",
        "inputs": ["nb pieces", "puissance", "marque pref"],
        "outputs": ["devis partenaires"],
        "ux": ["Dashboard", "fiche bien standing"],
        "functional": ["Lead multi-partenaires"],
        "data_model": ["ServiceRequest type=ac"],
        "api": ["POST /api/addons/ac-quote"],
        "monetization": "Commission installation + entretien.",
        "kpis": "quotes, install_close",
        "risks": "SAV partenaire — SLA contractuel.",
        "v1": "Lead",
        "later": "Catalogue SKU",
        "sources": [
            "https://batigoservices.com/",
            "https://namoryenergy.com/",
        ],
    },
    {
        "file": "20-kit-solaire.md",
        "title": "Kit solaire / onduleur",
        "priority": "P1",
        "category": "Énergie",
        "summary": "Estimation / devis kits solaires adaptés maison SN (coupures SENELEC).",
        "problem": "Factures + coupures; clim = gros consommateur pile aux heures solaires.",
        "market": "Fourchettes 2026 approx: 1–2 kWc 0,8–1,5M; 3 kWc 1,8–2,8M; 5–6 kWc 3,5–5,5M; 8–10 kWc 5,5–9M FCFA. Kits commerçants Dakar (Esotech etc.). Devis exemple ~3,5M pour 2 clim+frigo autonome.",
        "users": "Proprio, diaspora construisant",
        "synergy": "Simu construction; clim; bundle Maison Confort.",
        "inputs": ["conso_estimee", "nb_clim", "toit_m2"],
        "outputs": ["kit suggéré", "fourchette", "CTA installateur"],
        "ux": ["/outils/solaire", "post-construction checklist"],
        "functional": ["Barèmes kits", "lead partenaires"],
        "data_model": ["SolarKit"],
        "api": ["POST /api/addons/solar/simulate"],
        "monetization": "Commission installateur.",
        "kpis": "sim_to_quote",
        "risks": "Dimensionnement — visite technique obligatoire.",
        "v1": "Simulateur indicatif + leads",
        "later": "Pompe solaire forage combo",
        "sources": [
            "https://takoussane.com/panneaux-solaires-maison-senegal-guide-complet/",
            "https://esotech.sn/",
            "https://namoryenergy.com/",
        ],
    },
    {
        "file": "21-certification-docs.md",
        "title": "Coffre-fort documents / certification",
        "priority": "P1",
        "category": "Confiance",
        "summary": "Stockage sécurisé TF, bail, EDL, quittances, rapports diligence — partage contrôlé.",
        "problem": "Docs éparpillés WhatsApp; perte; falsification.",
        "market": "Attente diaspora + gestion pro (Noflaye: docs 24/7).",
        "users": "Tous rôles",
        "synergy": "Tous add-ons produisant PDF.",
        "inputs": ["fichiers", "métadonnées type"],
        "outputs": ["liens signés", "audit log"],
        "ux": ["Dashboard Documents"],
        "functional": ["S3", "ACL par rôle", "watermark option"],
        "data_model": ["Document", "DocumentAcl"],
        "api": ["upload/download signed URLs"],
        "monetization": "Inclus; premium retention longue.",
        "kpis": "docs_per_case",
        "risks": "RGPD/data residency; virus scan.",
        "v1": "Upload + roles",
        "later": "e-sign",
        "sources": ["https://www.noflaye.sn/", "docs/proptech-analysis.md"],
    },
    {
        "file": "22-portail-multi-biens.md",
        "title": "Portail multi-biens propriétaire",
        "priority": "P1",
        "category": "Gestion",
        "summary": "Vue portefeuille: loyers, vacance, tickets, ROI simple.",
        "problem": "Bailleurs multi-biens gèrent sur Excel/WhatsApp.",
        "market": "Noflaye / SysSamba / Diavix — table stakes gestion.",
        "users": "Propriétaire",
        "synergy": "Axe 4; PNO; reporting fiscal; estimation revente.",
        "inputs": ["biens sous mandat"],
        "outputs": ["dashboard KPIs"],
        "ux": ["/app/owner"],
        "functional": ["Agrégats paiements Wave/OM", "liste retards"],
        "data_model": ["Lease", "Payment", "Property"],
        "api": ["owner Graph/REST"],
        "monetization": "Inclus gestion; upsell premium.",
        "kpis": "MAU owner, retention_mandate",
        "risks": "Exactitude compta.",
        "v1": "Liste + loyers",
        "later": "ROI/fiscal export",
        "sources": [
            "https://www.noflaye.sn/",
            "https://syssamba.com/en",
            "https://diavix.com/",
        ],
    },
    {
        "file": "23-scoring-locataire.md",
        "title": "Garant / scoring locataire",
        "priority": "P1",
        "category": "Location / Risk",
        "summary": "Score interne à partir de KYC + historique paiements plateforme — réduit impayés et alimente cross-sell.",
        "problem": "Impayés = douleur n°1 bailleur; Cautiona mise sur scoring intelligent.",
        "market": "Historique on-platform après 12 mois = avantage vs classifieds.",
        "users": "Agence, bailleur",
        "synergy": "Caution; offre Axe 2/3 aux bons payeurs.",
        "inputs": ["dossier", "payment_history"],
        "outputs": ["score", "recommandation"],
        "ux": ["Back-office agence", "soft offer locataire"],
        "functional": ["Règles score v1", "pas de discrimination illégale — policy"],
        "data_model": ["TenantScore"],
        "api": ["GET /api/tenants/:id/score"],
        "monetization": "Meilleure rétention mandats gestion.",
        "kpis": "default_rate, upsell_accession",
        "risks": "Éthique/data; consentement.",
        "v1": "Score simple on-time ratio",
        "later": "Partage Cautiona",
        "sources": [
            "https://www.euroquity.com/en/company/cautiona",
            "docs/positioning.md",
        ],
    },
    {
        "file": "24-epargne-construction.md",
        "title": "Calendrier d'épargne construction",
        "priority": "P1",
        "category": "Accession",
        "summary": "Pendant le paiement du terrain, jauge d'épargne mensuelle vers le budget chantier (rappels Wave/SMS).",
        "problem": "Client finit de payer le terrain sans cash pour bâtir.",
        "market": "Pattern Senguka: save toward deposit; adapter en 'save toward build'.",
        "users": "Acquéreur étalé",
        "synergy": "Dashboard acquéreur; simu construction; pack constructeur.",
        "inputs": ["target_build_budget", "months"],
        "outputs": ["monthly_save", "progress bar", "reminders"],
        "ux": ["Jauge dashboard"],
        "functional": ["Goals", "notifications", "pas de custody fonds v1 (éducation)"],
        "data_model": ["SavingsGoal"],
        "api": ["CRUD goals"],
        "monetization": "Conversion pack construction.",
        "kpis": "goals_active, build_pack_conversion",
        "risks": "Ne pas détenir l'épargne sans agrément — v1 = coach + rappels.",
        "v1": "Rappels + tracking déclaré",
        "later": "Wallet partenaire MFI",
        "sources": [
            "https://senguka.com/",
            "docs/add-ons.md §10",
        ],
    },
]


def more_addons() -> list[dict]:
    """Remaining add-ons with solid but slightly shorter research notes."""
    rows = [
        ("25-plans-types.md", "Plans types / catalogues maisons", "P2", "Construction",
         "Catalogue plans 80/120/150 m² prêts pour permis.",
         "Plans catalogue ~100–500k FCFA; sur-mesure dès ~500k.",
         "https://www.ecsinformatique.com/quel-est-le-cout-de-realisation-de-plan-de-maison-en-2024/"),
        ("26-suivi-chantier.md", "Suivi de chantier léger", "P2", "Diaspora / BTP",
         "Rapports photo/vidéo périodiques + jalons — tiers indépendant.",
         "QualiBTP / SENIMMO / Jawudi-style milestone reporting pour diaspora.",
         "https://linkedin.com/company/qualibtp"),
        ("27-materiaux-marketplace.md", "Marketplace matériaux", "P3", "Construction",
         "Devis agrégés ciment, fer, carrelage via fournisseurs partenaires.",
         "Volume post-simu construction; commission fournisseurs.",
         "docs/add-ons.md"),
        ("28-credit-epargne-mfi.md", "Crédit / épargne construction (MFI)", "P3", "Finance",
         "Partenariat banque/MFI pour financer chantier — pas de bilan propre.",
         "Référencement seulement jusqu'à agrément.",
         "https://senguka.com/"),
        ("29-report-loyer.md", "Report / lissage de loyer", "P2", "Location / Fintech",
         "Aide ponctuelle locataire via partenaire (modèle Cautiona élargi).",
         "Réduit résiliation; fee partenaire.",
         "https://aps.sn/une-fintech-mise-sur-la-digitalisation-pour-faciliter-lacces-au-logement/"),
        ("30-demenagement-menage.md", "Déménagement / ménage", "P2", "Services locatifs",
         "Packs entrée/sortie: camion + cleaning.",
         "Annuaire déménageurs Dakar; bundle avec EDL.",
         "https://www.goafricaonline.com/sn/articles/405-changement-adresse-demenagement-dakar"),
        ("31-pack-meuble.md", "Pack meublé / kit premier logement", "P2", "Location",
         "Location ou vente kit meubles pour entrée rapide.",
         "Meublé Dakar souvent +40–100% vs vide; kit réduit friction.",
         "https://www.myafric.com/fr/louer-a-dakar-guide-complet-location/"),
        ("32-maintenance-marketplace.md", "Marketplace maintenance", "P2", "Gestion",
         "Tickets plomberie/clim/électrique depuis dashboard.",
         "Noflaye signalement + prestataires type Batigo.",
         "https://www.noflaye.sn/"),
        ("33-home-staging-photo.md", "Home staging / shoot photo", "P2", "Vente",
         "Shoot pro + retouche pour annonces et OG cards.",
         "Qualité visuelle = conversion; share cards docs/social-share-cards.md.",
         "docs/social-share-cards.md"),
        ("34-comparateur-frais.md", "Comparateur frais (transparence)", "P2", "Confiance",
         "Vue notaire + mutation + commission agence côte à côte.",
         "Différenciation vs classifieds opaques.",
         "https://nadiaimmoservices.blog/frais-notaire-senegal/"),
        ("35-escrow-sequestre.md", "Escrow / séquestre paiements", "P2", "Confiance / Diaspora",
         "Fonds chez notaire ou compte dédié; libération par jalons.",
         "MyAfric/Coupefile: jamais payer vendeur en direct; Jawudi escrow milestones.",
         "https://www.coupefile-immobilier.com/senegal-terrain-a-vendre-et-diaspora-comment-acheter-a-distance-en-confiance/"),
        ("36-conciergerie-bien-vide.md", "Conciergerie bien vide", "P2", "Diaspora",
         "Gardiennage, visites surprise, paiement factures pour biens inoccupés.",
         "Abonnement mensuel diaspora owners.",
         "docs/add-ons.md"),
        ("37-procuration-assist.md", "Assistance procuration (POA)", "P2", "Diaspora",
         "Guidance procuration limitée, légalisée, révocable + mandataire.",
         "MyAfric: pièce maîtresse achat à distance; ne pas sur-mandater.",
         "https://www.myafric.com/fr/procuration-achat-immobilier-senegal/"),
        ("38-reporting-fiscal.md", "Reporting fiscal annuel proprio", "P2", "Gestion",
         "Récap loyers/charges pour déclaration.",
         "Noflaye liste déjà récap fiscal annuel.",
         "https://www.noflaye.sn/"),
        ("39-annonces-boost.md", "Boost SEO / social annonces", "P2", "Marketing",
         "OG cards + packs boost diffusion WhatsApp/FB/TikTok.",
         "docs/social-share-cards.md — 3 crops.",
         "docs/social-share-cards.md"),
        ("40-white-label.md", "White-label branche / agence partenaire", "P3", "B2B",
         "Même stack sous marque partenaire — fee SaaS.",
         "Scale réseau d'agences sans diluer catalogue qualité.",
         "docs/tech-stack.md"),
        ("41-forage-eau.md", "Forage / adduction eau", "P2", "Viabilisation",
         "Mise en relation forage + pompe (solaire option).",
         "Coût forage souvent ~1–5M+ FCFA selon profondeur/sol; étude hydrogéologique.",
         "https://senegal-forage.com/cout-forage-senegal-guide-conseils/"),
        ("42-vrd-viabilisation.md", "VRD / viabilisation lot", "P2", "Viabilisation",
         "Voirie, réseaux divers, assainissement via entreprises infra.",
         "Partenaires type In'O; devis site-specific.",
         "https://ino.sn/"),
        ("43-regularisation-tf.md", "Régularisation / montée en titre foncier", "P2", "Foncier",
         "Accompagnement bail/PO → TF via circuit admin/notaire.",
         "Immatriculation encadrée; NICAD central (décret 2012-396).",
         "https://immoconnexion.com/acheter-un-terrain-au-senegal/"),
        ("44-cloture-portail.md", "Clôture & portail", "P2", "Viabilisation",
         "Devis clôture linéaire + portail — premier travaux visibles.",
         "Option simu prêt-à-bâtir; partenaires ferrailleurs/maçons.",
         "docs/add-ons.md"),
        ("45-groupe-electrogene.md", "Groupe électrogène / stabilisateur", "P2", "Énergie",
         "Pour meublés/standing en appoint des coupures.",
         "Complément solaire; lead électriciens.",
         "https://namoryenergy.com/"),
        ("46-contrat-entretien.md", "Contrat entretien multi-technique", "P2", "Gestion",
         "Abonnement clim+élec+plomberie facturé au proprio.",
         "Batigo-style maintenance contracts.",
         "https://batigoservices.com/"),
        ("47-colocation-matching.md", "Colocation / coliving matching", "P2", "Location",
         "Matching collocataires pour F2/F3 Dakar.",
         "Remplit plus vite; Noflaye gère déjà coloc multi-locataires.",
         "https://www.noflaye.sn/"),
        ("48-preavis-remise-cles.md", "Préavis & remise des clés pack", "P2", "Gestion",
         "Ménage + EDL sortie + relance annonce à relouer.",
         "Réduit vacance locative.",
         "docs/add-ons.md"),
        ("49-location-saisonniere.md", "Location saisonnière / meublé diaspora", "P2", "Location",
         "Calendrier + conciergerie Petite Côte (Saly…).",
         "Saly: ~35–150k FCFA/nuit selon saison; permis tourisme si gros volume.",
         "https://www.loger-dakar.com/location-saisonniere-saly-touristes-et-investisseurs/"),
        ("50-co-acquisition.md", "Co-acquisition familiale", "P2", "Accession",
         "2–4 payeurs sur un même échéancier étalé.",
         "Très courant diaspora/famille élargie.",
         "docs/first analysis/q3.md"),
        ("51-reprise-etale.md", "Transfert / reprise dossier étalé", "P2", "Accession",
         "Remise en vente après défaillance selon clause résolutoire.",
         "Process juridique déjà prévu en analyse; UX statut dossier.",
         "docs/first analysis/q1.md"),
        ("52-carte-prix-m2.md", "Carte prix/m² par quartier", "P2", "Discovery / SEO",
         "Couche map chaleurs prix pour comps et estimation.",
         "Différenciant vs list-only classifieds; alimente AVM léger.",
         "docs/proptech-analysis.md"),
    ]
    out = []
    for file, title, priority, category, summary, market, source in rows:
        out.append({
            "file": file,
            "title": title,
            "priority": priority,
            "category": category,
            "summary": summary,
            "problem": summary,
            "market": market,
            "users": "Selon parcours (voir docs/add-ons.md §10.2)",
            "synergy": "Voir matrice axes × add-ons dans docs/add-ons.md",
            "inputs": ["Voir formulaire dédié — à détailler en implémentation"],
            "outputs": ["Lead / devis / statut dossier"],
            "ux": ["Surfaces listées dans docs/add-ons.md §10.5"],
            "functional": [
                "Mode partenaire (lead) par défaut",
                "Statuts request → quoted → done",
                "Documents au coffre-fort si applicable",
            ],
            "data_model": ["ServiceRequest", "Partner"],
            "api": [f"POST /api/addons/{file.replace('.md','').split('-',1)[1]}/request"],
            "monetization": "Commission partenaire ou forfait agence",
            "kpis": "requests, conversion, revenue_attach",
            "risks": "Qualité partenaire; disclaimers; pas d'exécution BTP en propre",
            "v1": "Lead + tracking",
            "later": "Paiement in-app / SLA",
            "sources": [source, "docs/add-ons.md"],
        })
    return out


def render(a: dict) -> str:
    def bullets(items):
        if isinstance(items, str):
            return items
        return "\n".join(f"- {x}" for x in items)

    return f"""# {a['title']}

| Champ | Valeur |
| --- | --- |
| **ID fichier** | `{a['file']}` |
| **Priorité** | **{a['priority']}** |
| **Catégorie** | {a['category']} |
| **Synthèse** | {a['summary']} |

## 1. Problème client

{a['problem']}

## 2. Réalité marché (recherche)

{a['market']}

## 3. Utilisateurs & synergies

- **Users:** {a['users']}
- **Synergie produit:** {a['synergy']}

## 4. Inputs

{bullets(a['inputs'])}

## 5. Outputs

{bullets(a['outputs'])}

## 6. UX / surfaces

{bullets(a['ux'])}

## 7. Spec fonctionnelle

{bullets(a['functional'])}

## 8. Données

{bullets(a['data_model'])}

## 9. API (cible)

{bullets(a['api'])}

## 10. Monétisation

{a['monetization']}

## 11. KPIs

{a['kpis']}

## 12. Risques & conformité

{a['risks']}

## 13. Phasing

- **v1:** {a['v1']}
- **Plus tard:** {a['later']}

## 14. Sources

{bullets(a['sources'])}

---

*Spec générée pour l'agence full-service SN — voir aussi `docs/add-ons.md`, `docs/positioning.md`.*
"""


def main() -> None:
    all_addons = ADDONS + more_addons()
    index_lines = [
        "# Specs add-ons (1 fichier = 1 add-on)",
        "",
        "Dossier généré avec recherches web marché Sénégal / Afrique (construction, caution, solaire, diaspora, notaire, forage, etc.).",
        "",
        "| # | Add-on | Priorité | Fichier |",
        "| --- | --- | --- | --- |",
    ]
    for i, a in enumerate(all_addons, 1):
        path = OUT / a["file"]
        path.write_text(render(a), encoding="utf-8")
        index_lines.append(
            f"| {i} | {a['title']} | {a['priority']} | [`specs/{a['file']}`](./specs/{a['file']}) |"
        )
    index_lines += [
        "",
        "## Comment utiliser",
        "",
        "1. Lire l'overview [`../add-ons.md`](../add-ons.md) (anciennement à la racine docs — voir lien).",
        "2. Implémenter d'abord les **P0** puis **P1**.",
        "3. Chaque spec contient: problème, marché, inputs/outputs, UX, data, API, monetization, KPIs, risques, sources.",
        "",
    ]
    (OUT.parent / "README.md").write_text("\n".join(index_lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(all_addons)} specs to {OUT}")


if __name__ == "__main__":
    main()
