/** 14 régions administratives du Sénégal. */
export const SENEGAL_REGIONS = [
  "Dakar",
  "Diourbel",
  "Fatick",
  "Kaffrine",
  "Kaolack",
  "Kédougou",
  "Kolda",
  "Louga",
  "Matam",
  "Saint-Louis",
  "Sédhiou",
  "Tambacounda",
  "Thiès",
  "Ziguinchor",
] as const;

export type SenegalRegion = (typeof SENEGAL_REGIONS)[number];

/** Heuristique ville → région pour seed / préremplissage. */
export function guessRegionForCity(city: string): SenegalRegion | null {
  const map: Record<string, SenegalRegion> = {
    Dakar: "Dakar",
    Pikine: "Dakar",
    Guédiawaye: "Dakar",
    Rufisque: "Dakar",
    "Keur Massar": "Dakar",
    Bargny: "Dakar",
    Bambilor: "Dakar",
    Sébikotane: "Dakar",
    Diamniadio: "Dakar",
    Thiès: "Thiès",
    Mbour: "Thiès",
    Saly: "Thiès",
    Tivaouane: "Thiès",
    Khombole: "Thiès",
    Pout: "Thiès",
    "Joal-Fadiouth": "Thiès",
    Ngaparou: "Thiès",
    Somone: "Thiès",
    Popenguine: "Thiès",
    Nguékhokh: "Thiès",
    "Saint-Louis": "Saint-Louis",
    "Richard-Toll": "Saint-Louis",
    Dagana: "Saint-Louis",
    Podor: "Saint-Louis",
    Kaolack: "Kaolack",
    "Nioro du Rip": "Kaolack",
    Guinguinéo: "Kaolack",
    Ziguinchor: "Ziguinchor",
    Bignona: "Ziguinchor",
    Oussouye: "Ziguinchor",
    Touba: "Diourbel",
    Mbacké: "Diourbel",
    Diourbel: "Diourbel",
    Bambey: "Diourbel",
    Fatick: "Fatick",
    Foundiougne: "Fatick",
    Gossas: "Fatick",
    Louga: "Louga",
    Linguère: "Louga",
    Kébémer: "Louga",
    Tambacounda: "Tambacounda",
    Bakel: "Tambacounda",
    Goudiry: "Tambacounda",
    Koumpentoum: "Tambacounda",
    Kolda: "Kolda",
    Vélingara: "Kolda",
    "Médina Yoro Foulah": "Kolda",
    Matam: "Matam",
    Kanel: "Matam",
    Ranérou: "Matam",
    Kaffrine: "Kaffrine",
    Koungheul: "Kaffrine",
    Birkelane: "Kaffrine",
    "Malem Hoddar": "Kaffrine",
    Kédougou: "Kédougou",
    Salémata: "Kédougou",
    Saraya: "Kédougou",
    Sédhiou: "Sédhiou",
    Goudomp: "Sédhiou",
    Bounkiling: "Sédhiou",
  };
  return map[city] ?? null;
}
